# Generated by Django 3.1 on 2020-09-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
