# Generated by Django 3.1 on 2020-12-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a',
            old_name='rollno',
            new_name='rollNo',
        ),
    ]
