# Generated by Django 3.1 on 2020-09-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'faculty'},
        ),
        migrations.AlterModelTable(
            name='faculty',
            table='Collegefaculty',
        ),
    ]
