# Generated by Django 3.1 on 2020-09-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'student'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Collegestudent',
        ),
    ]
